name: Standard RB
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  standard:
    name: Standard RB Check Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Run Standard RB
      run: bundle exec standardrb --format progress
